### ISSUE TITLE
`bat` fails to open file starting with `#` 

### ISSUE THREAD

**Issue by aguadopd** [bigH/git-fuzzy#11]
![image](https://user-images.githubusercontent.com/5558299/83687332-fe2f3800-a5c1-11ea-81a3-71c1ea9e9ed5.png)

Scripts should quote filenames? Maybe `fzf` is the one to blame.

**Comment by bigH** [comment]
this is [fixed](https://github.com/bigH/git-fuzzy/commit/82acd8906501ad44d3d680500eda0638fb063d25)
