### ISSUE TITLE
Feature request: staging hunks

### ISSUE THREAD

**Issue by asymmetric** [bigH/git-fuzzy#12]
It would be really cool to be able to stage hunks (parts of a diff) indepedently, simliar to the workflow exposed by `git add -p`.

**Comment by bigH** [comment]
I want this too. It'll take some time to write code that will split diffs into hunks and make it nice.

There is [`splitpatch`](https://github.com/benjsc/splitpatch). However, it's GPL-2 and therefore incompatible with MIT license of this project. I could expect that folks have this installed, but I find the file-based interface to be non-ideal.

**Comment by asymmetric** [comment]
@HirenHiranandani-at has this been implemented?
