### ISSUE TITLE
Page/scroll up & down the right diff pane: needs keybinding configurability and in-app exposure

### ISSUE THREAD

**Issue by ronjouch** [bigH/git-fuzzy#2]
When viewing a commit or a file in a commit (viewed with `delta` + `bat`), I couldn't find how to scroll down/up the diff in the right side of the screen (to view more than the first page of the diff). Here's what I intuitively tried:

- PgDown, but it pages down the fzf cursor in the list of commits (left side)
- Space/n/p/j/k, but it edits the query
- Enter (thinking maybe I'd enter a mode of acting on the diff?), but it comes _back_ to the main menu.

I'm sure there is a keyboard binding, but I couldn't find it, neither in the tool itself nor in the readme. It would be nice if it was explicitly listed in the top-left summary of the bindings (near`∆ working copy  Ctrl-P`, `∆ merge-base  Alt-P`, etc.)

Thanks for the nifty tool! In particular, lack of [delta/diff-so-fancy support in tig](https://github.com/jonas/tig/issues/542) makes me like git-fuzzy 🙂.

**Comment by zatnas** [comment]
`Shift-Up` & `Shift-Down`

**Comment by ronjouch** [comment]
> `Shift-Up` & `Shift-Down`

@zethnest thanks! Notes to maintainer or passerbys:

1. I cannot use these bindings, in [my terminal](https://sw.kovidgoyal.net/kitty/) both are bound to move between terminal panes...
2. ... so, I'd love to be able to configure bindings ...
3. ... and it might still be useful to explicitly list these kinda-unusual bindings in the top-left "self-documenting" summary (near `∆ working copy Ctrl-P`, `∆ merge-base Alt-P`, etc.).

**Comment by dandavison** [comment]
I found that mouse/trackpad scroll also does it.

**Comment by sprytnyk** [comment]
These shotcuts work too:
<kbd>Ctrl</kbd> + <kbd>e</kbd> - scroll up
<kbd>Ctrl</kbd> + <kbd>y</kbd> - scroll down

Navigation:
<kbd>Ctrl</kbd> + <kbd>k</kbd> - go up
<kbd>Ctrl</kbd> + <kbd>j</kbd> - go down

**Comment by yermulnik** [comment]
@vald-phoenix Kudos for <kbd>ctrl + e</kbd> and <kbd>ctrl + y</kbd>.

And +1 for an option to re-define these.

Also are there any keybinding to move right pane left and right as it doesn't wrap long lines.

**Comment by sprytnyk** [comment]
As for now, it looks like it's possible to redefine keybindings manually in the following files:
- lib/modules/reflog.sh
- lib/modules/log.sh
- lib/modules/branch.sh
- lib/modules/status.sh
- lib/modules/hub/pr.sh
- lib/core.sh

> Also are there any keybinding to move right pane left and right as it doesn't wrap long lines.

As for that, this seems to be a primary limitaion of `fzf` by itself: https://github.com/junegunn/fzf/issues/756

**Comment by bigH** [comment]
the project has been updated to make the key bindings configurable. [example](https://github.com/bigH/git-fuzzy/blob/master/lib/modules/log.sh#L3)
