### ISSUE TITLE
Fails on initialized git repositories without commits

### ISSUE THREAD

**Issue by FichteFoll** [bigH/git-fuzzy#24]
Running `git fuzzy` on a newly initialized repository fails with the message "not in a git repo", while normal git commands like `git status` obviously work fine. Not sure if this is an oversight.

Note: `git s` is an alias to `git status`
```
~/builds/git-fuzzy-git Δ git s
A  .SRCINFO
A  PKGBUILD
?? git-fuzzy/

~/builds/git-fuzzy-git ♦ git fuzzy status
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[ERR] not in git repo
 ?=1
```

On another note, I just submitted this to the AUR https://aur.archlinux.org/packages/git-fuzzy-git/.

**Comment by bigH** [comment]
this has been fixed (don't remember when/how).
