### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by fornof** [bigH/git-fuzzy#26]
just wondering if there's native powershell support.
thanks.

**Comment by bigH** [comment]
this will probably work in WSL. feel free to try it.

i don't expect powershell to work since this requires bash.
edit: windows support is not planned or likely.

**Comment by gtbuchanan** [comment]
For what it's worth, [PSFzf](https://github.com/kelleyma49/PSFzf) has [a few undocumented implementations](https://github.com/kelleyma49/PSFzf/blob/master/PSFzf.Git.ps1#L89-L130):
* Branches
* Files
* Hashes/Log
* PRs
* Stashes
* Tags

And [one somewhat documented one](https://github.com/kelleyma49/PSFzf/blob/master/docs/Invoke-FuzzyGitStatus.md):
* Status

Here's an example for `git log`:

<img width="2999" height="920" alt="Image" src="https://github.com/user-attachments/assets/4e7fa7f5-73dd-45a8-9fde-5fd58462c02c" />

Here's an example for `git status`:

<img width="2998" height="921" alt="Image" src="https://github.com/user-attachments/assets/01a9f813-2863-4f61-8e2a-b3bfe6d77b06" />
