### ISSUE TITLE
Disable checkout less restrictively

### ISSUE THREAD

**Issue by przepompownia** [bigH/git-fuzzy#28]
https://github.com/bigH/git-fuzzy/blob/ecdcd157e537d98586435a40bed83d40c65bd959/lib/modules/branch.sh#L20

I would like to checkout a branch also when there are unversioned files (and sometimes even when there are modified ones), with possible rejection at git level. 

Thanks for useful tool!

**Comment by bigH** [comment]
this was because there would be no user feedback or it'd be too expensive to provide; please submit a PR if you have a solution.
