### ISSUE TITLE
Install with brew?

### ISSUE THREAD

**Issue by thedrow** [bigH/git-fuzzy#3]
It'd be easier to use this if it was installable with Homebrew.
Can you submit a formula?

**Comment by thedrow** [comment]
Oh and I just tested this and it is AWESOME!
Thank you so much.

**Comment by jonleopard** [comment]
@thedrow I think this falls more in the scope of a zsh plugin. If you use a plugin manager, you could install with that.  Perhaps some install instructions with either [antibody](https://getantibody.github.io/) or [z-plug ](https://github.com/zplug/zplug) would be useful?

**Comment by thedrow** [comment]
I use it just fine with bash.

**Comment by thedrow** [comment]
In addition, pyenv and other shell related tools can be installed using homebrew.
I see no reason why git-fuzzy is an exception.

**Comment by cheerfulstoic** [comment]
I'm fine install with whatever, but I don't see any instructions in the `README`...  What am I missing?

**Comment by cheerfulstoic** [comment]
Skipped past the `zsh` section because I use `bash`.  Made this PR: https://github.com/bigH/git-fuzzy/pull/14

**Comment by cheerfulstoic** [comment]
Thinking on it, though, I think installation with `brew` would be better because it's made to deal with versions.  This tool seems great, but I've never installed anything like this before and I'll probably just be confused for a little while the next time I come back to update / change it for whatever reason

**Comment by bigH** [comment]
lots of instructions available now on ways to install. closing this. PRs for brew support are welcome :)
