### ISSUE TITLE
Help section hides the git command result below on small height terminal

### ISSUE THREAD

**Issue by Morikko** [bigH/git-fuzzy#41]
![2021-07-26_09-09 git fuzzy help](https://user-images.githubusercontent.com/7831572/126947428-d22359d7-b18d-4706-b6d8-d3e5712c6c99.png)

The help section is very helpful and beautiful :) However it takes so much space that in an IDE integrated terminal, I often did not see the list below.

Would it be possible to add a setting to hide it and maybe a shortcut to toggle it ? Also, an idea is to make it visible on terminal with the height bigger than a size to define ?

The same for the git command. I am not sure it is very helpful on a daily basis for every body. Maybe it would be worth making it visible as a setting (even debug ?) or shortcut.

> Any time git command output is used in preview or listing, there is a header with the command run **(useful for copy-pasting or just knowing what's happening)**. You can optionally enable debugging switches to see other commands being run in the background or how commands are routed.

The copy/paste use case is a bit broken because one will miss all the parameters passed through variable like `GF_LOG_MENU_PARAMS`

**Comment by HirenHiranandani-at** [comment]
Fixed by https://github.com/bigH/git-fuzzy/pull/45
