### ISSUE TITLE
Feature request: git log --patch fuzzy find 

### ISSUE THREAD

**Issue by jqhr** [bigH/git-fuzzy#44]
I want to find file change log by git log, bug git commit message was so simple and short, I like fzf , but I have not find any way to solute it. I think somebody also like this feature.

**Comment by HirenHiranandani-at** [comment]
I'm sorry I don't really know what you're asking. If you use `git fuzzy log`, you can interactively change the command to filter (e.g `-G foo` searches patches for additions/removals of 'foo')
