### ISSUE TITLE
Fixup

### ISSUE THREAD

**Issue by iloveitaly** [bigH/git-fuzzy#49]
Would be awesome to add fixup as an option to the git commit view. Ability to select which commit (filtered by those that have edited the file(s) in staging) to fixup against.

**Comment by bigH** [comment]
I think that's a great idea. I have thought about this a lot myself. I feel implementing this would mean expanding to the next "ring of functionality". That is going to be a lot of work and something I'm not able to take on today.

You're free to create a PR if this is something you desperately need. You should be able to trace from [here](https://github.com/bigH/git-fuzzy/blob/36fc08f084a0cabf3e381dbbbce8e3a1a22fbaa4/lib/modules/status.sh#L6) to figure out how to add new functionality to the `status` sub-command. It's actually quite straight forward once you understand things.

`git fuzzy helper` commands like [this one](https://github.com/bigH/git-fuzzy/blob/36fc08f084a0cabf3e381dbbbce8e3a1a22fbaa4/lib/modules/status.sh#L43) get rewritten to calls to `gf_helper_[helper name]` functions like [this one](https://github.com/bigH/git-fuzzy/blob/36fc08f084a0cabf3e381dbbbce8e3a1a22fbaa4/lib/modules/helpers/status.sh#L59).

All you need to do is:

0. add a variable for the binding if you like
1. add a binding to the `fzf` call in `lib/modules/status.sh` that calls a helper like the others
2. implement the helper you call above in `lib/modules/helpers/status.sh`
