### ISSUE TITLE
Allow custom key bindinding

### ISSUE THREAD

**Issue by mijailr** [bigH/git-fuzzy#7]
Hello, I will like to have a way to define my own key binding, since I'm on  MacOS, we don't have the ALT key. So the current key mapping doesn't work.

BTW, very good tool, thanks!

**Comment by adil-uddin** [comment]
@mijailr so we can't use it in MacOS now ? I tried to use this, fuzzy status displays diff files but I'm unable to stage or commit from there.

**Comment by pnw** [comment]
In Iterm2 I've mapped the option key to Esc+. That seems to work well enough.

<img width="1007" alt="Preferences" src="https://user-images.githubusercontent.com/1459213/83688570-dd0f1d00-a5aa-11ea-9fd9-31239e3e2f19.png">

**Comment by bigH** [comment]
merged the change. thank you!
